# Generated by Django 4.1.11 on 2023-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/static/defaults/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
