# Generated by Django 4.1.11 on 2023-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='static/defaults/default.png', upload_to='images/%Y/%m/%d/'),
        ),
    ]
